# Generated by Django 5.1.2 on 2024-10-16 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_pedido_adicional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='adicional',
        ),
    ]
